
options:
  max-time: 5

pipelines:
  default:
    - step:
        script:
          - echo 'In the future, Python tests will be run here.'
  tags:
    v*:
      - step:
          name: Deploy to Docker Hub
          image: python:3.7
          services: [docker]
          deployment: container
          script:
            - export TAG=${BITBUCKET_TAG#v}
            - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
            - docker build --build-arg version=$TAG -t cccs/assemblyline-service-cuckoo:$TAG -t cccs/assemblyline-service-cuckoo:latest .
            - docker push cccs/assemblyline-service-cuckoo
