name: tests

trigger: ["*"]
pr: ["*"]

pool:
  vmImage: 'ubuntu-18.04'

jobs:
- job: run_test
  strategy:
    matrix:
      python3_7:
        python.version: '3.7'
      Python3_8:
        python.version: '3.8'

  timeoutInMinutes: 10

  steps:
    - task: UsePythonVersion@0
      displayName: Set python version
      inputs:
        versionSpec: '$(python.version)'
    - script: |
        install_path=`pwd`
        sudo apt-get update
        sudo apt-get install -y qemu-utils
        sudo rm -rf /var/lib/apt/lists/*
        sudo env "PATH=$PATH" python -m pip install -U --no-cache-dir assemblyline assemblyline_v4_service jinja2 retrying pefile ip2geotools -r `pwd`/requirements.txt
        sudo env "PATH=$PATH" python -m pip install -U -r `pwd`/test/requirements.txt
        sudo rm -rf /tmp/* /var/lib/apt/lists/* ~/.cache/pip
      displayName: Setup environment
    - script: python -m pytest --durations=10 -rsx -vv --cov-report=xml --cov=cuckoo
      displayName: Test
    - script: python -m codecov
      displayName: Upload Coverage